function drawUAV(uu)
V = [...
        5, 0, 0; ...
        3, 1, -1; ...
        3, -1, -1; ...
        3, -1, 1; ...
        3, 1, 1; ...
        -4, 0, 0; ...
        1, 4, 0; ...
        -1, 4, 0; ...
        -1, -4, 0; ...
        1, -4, 0; ...
        -3, 2, 0; ...
        -4, 2, 0; ...
        -4, -2, 0; ...
        -3, -2, 0; ...
        -3, 0, 0; ...
        -4, 0, -2; ...
   ];

% define faces as a list of vertices numbered above
F = [...
        1, 2, 3, 1; ...
        1, 3, 4, 1; ...
        1, 4, 5, 1; ...
        1, 2, 5, 1; ...
        2, 3, 6, 2; ...
        3, 4, 6, 3; ...
        4, 5, 6, 4; ...
        2, 5, 6, 2; ...
        7, 8, 9, 10; ...
        11, 12, 13, 14; ...
        6, 15, 16, 6; ...
    ];


% define colors for each face    
  myred = [1, 0, 0];
  mygreen = [0, 1, 0];
  myblue = [0, 0, 1];
  myyellow = [1, 1, 0];
  mycyan = [0, 1, 1];

  patchcolors = [...
    myred;...    
    mygreen;...  
    myblue;...   
    myyellow;... 
    myred;...    
    mygreen;...  
    myblue;...   
    myyellow;... 
    mycyan;...   
    mycyan;...   
    mycyan;...
    ];

    % process inputs to function
    pn       = uu(1);       % inertial North position     
    pe       = uu(2);       % inertial East position
    pd       = uu(3);           
    u        = uu(4);       
    v        = uu(5);       
    w        = uu(6);       
    phi      = uu(7);       % roll angle         
    theta    = uu(8);       % pitch angle     
    psi      = uu(9);       % yaw angle     
    p        = uu(10);       % roll rate
    q        = uu(11);       % pitch rate     
    r        = uu(12);       % yaw rate    
    t        = uu(13);       % time

    % define persistent variables 
    persistent uav_handle;
    
    % first time function is called, initialize plot and persistent vars
    if t==0,
        figure(1), clf
        uav_handle = drawUAVBody(V,F,patchcolors,...
                                               pn,pe,pd,phi,theta,psi,...
                                               [],'normal');
        title('UAV')
        xlabel('East')
        ylabel('North')
        zlabel('-Down')
        view(32,47)  % set the view angle for figure
        axis([-50,50,-10,100,-10,10]);
        hold on
        
    % at every other time step, redraw base and rod
    else 
        drawUAVBody(V,F,patchcolors,...
                           pn,pe,pd,phi,theta,psi,...
                           uav_handle);
    end
end

  
%=======================================================================
% drawUAVBody
% return handle if 3rd argument is empty, otherwise use 3rd arg as handle
%=======================================================================
%
function handle = drawUAVBody(V,F,patchcolors,...
                                     pn,pe,pd,phi,theta,psi,...
                                     handle,mode)
  V = rotate(V', phi, theta, psi)';  % rotate spacecraft
  V = translate(V', pn, pe, pd)';  % translate spacecraft
  % transform vertices from NED to XYZ (for matlab rendering)
  R = [...
      0, 1, 0;...
      1, 0, 0;...
      0, 0, -1;...
      ];
  V = V*R;
  
  if isempty(handle),
  handle = patch('Vertices', V, 'Faces', F,...
                 'FaceVertexCData',patchcolors,...
                 'FaceColor','flat',...
                 'EraseMode', mode);
  else
    set(handle,'Vertices',V,'Faces',F);
    drawnow
  end
end

%%%%%%%%%%%%%%%%%%%%%%%
function XYZ=rotate(XYZ,phi,theta,psi)
  % define rotation matrix
  R_roll = [...
          1, 0, 0;...
          0, cos(phi), -sin(phi);...
          0, sin(phi), cos(phi)];
  R_pitch = [...
          cos(theta), 0, sin(theta);...
          0, 1, 0;...
          -sin(theta), 0, cos(theta)];
  R_yaw = [...
          cos(psi), -sin(psi), 0;...
          sin(psi), cos(psi), 0;...
          0, 0, 1];
  R = R_yaw*R_pitch*R_roll;
  % rotate vertices
  XYZ = R*XYZ;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% translate vertices by pn, pe, pd
function XYZ = translate(XYZ,pn,pe,pd)
  XYZ = XYZ + repmat([pn;pe;pd],1,size(XYZ,2));
end

  